#!/usr/bin/env bash
# clean_tds dedupes identical files and permanently deletes trash

${CLEAN_DEST,,} && { echo -e "STARTING DEDUPE of identical files from $dest\n"
  rclone dedupe skip $dest -v --drive-use-trash=false --no-traverse --tpslimit=5
  echo -e "PERMANENTLY DELETING TRASH from $dest1\n"
  rclone delete $dest1: -vv --drive-trashed-only --drive-use-trash=false --tpslimit=5
  echo -e "REMOVING EMPTY DIRECTORIES from $dest\n"
  rclone rmdirs $dest -v --drive-use-trash=false --fast-list --tpslimit=5 --leave-root ; }

${CLEAN_SRC,,} = true ] && { echo -e "STARTING DEDUPE of identical files from $src\n"
  rclone dedupe skip $src -v --drive-use-trash=false --no-traverse --tpslimit=5
  echo -e "PERMANENTLY DELETING TRASH from $src1\n"
  rclone delete $src1: -vv --drive-trashed-only --drive-use-trash=false --tpslimit=5
  echo -e "REMOVING EMPTY DIRECTORIES from $src\n"
  rclone rmdirs $src -v --drive-use-trash=false --fast-list --tpslimit=5 --leave-root ; }
