#!/usr/bin/env bash
# This is a standalone script that will show you how sasync will read your set files
# Syntax is ./readsets set.videos <= substituting your set file name/location
echo;echo == CHECKING IF YOUR SETS CAN BE READ CORRECTLY BY SASYNC ==;echo
source ./sasync.conf

process_sets () {
  for set_file in $@; do
    echo Set file=$SETS_FOLDER/$set_file
    grep -v "#" $SETS_FOLDER/$set_file>sync_sets
    cat sync_sets
    while IFS=$' \t\n' read -r sync src dest maxtrans set_flags; do
    echo READ:  $sync $src $dest $maxtrans $set_flags
    done < sync_sets
  done
}

process_sets $@
echo == READ SETS COMPLETED ==;echo
