#!/usr/bin/env bash

# Initialize vars and folders. DO NOT CHANGE

#[[ ":$PATH:" != *":/path/to/add:"* ]] && PATH="/path/to/add:${PATH}"
[[ ":$PATH:" != *":sasync:"* ]] && PATH="$SASDIR:$SETDIR:${PATH}"

#  set_clean=$(column -t -s '\,' $SETDIR/$set_file | sed '/^\s*#.*$/d' | tee /dev/tty)
  set_clean=$(column -t -s '\,' $SETDIR/$set_file | sed '/^\s*#.*$/d;s/\r//g' | tee /dev/tty)

#  set_clean=$(column -t -s '\,' $SETDIR/$set_file | grep -o '^[^#]*' | tee /dev/tty)
  [ $EXIT_ON_BAD_PAIR = true ] && CON_EX="exit" || CON_EX="continue"

  STD_LOG="$SASDIR/logs/stdout_$set_file.log"
  ERR_LOG="$SASDIR/logs/stderr_$set_file.log"
  FAIL_LOG="$SASDIR/logs/fail_$set_file.log";>$FAIL_LOG

  [ ! -f $SASDIR/json.count ] && echo $MIN_JS >$SASDIR/json.count

  mkdir -p $SASDIR/config_backup $SASDIR/logs
  cp $SASDIR/sasync.conf $SASDIR/config_backup/sasync.conf_$(date +%y%m%d)
  find $SASDIR/config_backup/sasync.conf* -type f -mtime +14 -exec rm {} \;

  # End of Init
  . msg conf_ok
