#!/usr/bin/env bash
# Clean set file and initialize variables, log files and config backup file

if [ "$1" = "-c" ];then CFILE=$2;shift 2;fi
set_file=$1;shift;cmd_flags=$@
. sasync.conf.default
. "${CFILE:-sasync.conf}"
. msg start
if "$EXIT_ON_BAD_PAIR";then CON_EX="exit";else CON_EX="return 1";fi

if grep -E '\||,' $SETDIR/$set_file &>/dev/null;then IFS1=',|';fi
set_clean=$(sed '/#/d; /^$/d; s/[\t\r]/ /g; s/\"//g' "$SETDIR/$set_file")
echo -e "$set_clean" | column -s"$IFS1" -t

STD_LOG="$SASDIR"/logs/$(date +%F-%T)_stdout_"$set_file".log
ERR_LOG="$SASDIR"/logs/$(date +%F-%T)_stderr_"$set_file".log
FAIL_LOG="$SASDIR"/logs/$(date +%F-%T)_fail_"$set_file".log
if [ ! -f $SASDIR/json.count ];then echo $MINJS >$SASDIR/json.count;fi

mkdir -p $SASDIR/backup $SASDIR/logs
cp $SASDIR/sasync.conf "$SASDIR/backup/sasync.conf_$(date +%y%m%d)"
find $SASDIR/backup/sasync.conf* -type f -mtime +14 -exec rm {} \;

dsaf="--drive-service-account-file"
. msg init_complete
