#!/usr/bin/env bash
# size_calc calculates source and destination size

echo -e "\nCHECKING SIZE of $src and $dest BE PATIENT"
srcsize=`rclone size $src --json | cut -d ":" -f3 | cut -d "}" -f1`
srcsizeGB=$(( $srcsize/1024**3 ))
destsize=`rclone size $dest --json | cut -d ":" -f3 | cut -d "}" -f1`
destsizeGB=$(( $destsize/1024**3 ))
srcdestdiff=$(( $srcsize-$destsize ))
srcdestdiffGB=$(( $srcdestdiff/1024**3 ))

echo $srcsizeGB GB = $srcsize bytes = SIZE of SOURCE $src
echo $destsizeGB GB = $destsize bytes = SIZE of DEST $dest
echo -e "DIFF is $srcdestdiffGB GB = $srcdestdiff bytes"

MAXT=${maxtrans::-1}
SAs=$(( ($MAXT+${srcdestdiffGB#-}-1)/$MAXT ))
echo -e "Estimated number of SAs is $SAs with Max Transfer = $maxtrans\n"
