#!/bin/bash
echo;echo == STARTING SWEEP OF NON-SERVER-SIDE FILES ==;echo
if [ $SWEEP == "TRUE" ]; then
  export EXCL="--exclude-from "$SASYNC_FOLDER/exclude_none.txt
  export DMC="--disable move,copy"
  source sacalc
  for SA in $(seq 1 $SAs); do run_rclone_w_flags; done
  source ./sasync.conf
fi
