#!/bin/bash
# You can copy or download this script to install sasync, apply ownership and set USER and GROUP
# Modify USER and GROUP values for your own setup
# https://github.com/88lex/sasync
USER=seed
GROUP=seed
# Make Directories
echo "Making Directories"
sudo mkdir -p /opt/sasync/ /opt/sa
sudo chown -R $USER:$GROUP /opt/sasync/ /opt/sa
echo "downloading sasync"
git clone https://github.com/88lex/sasync.git /opt/sasync/
sudo chmod 775 /opt/sasync/sasync
sudo chmod 775 /opt/sasync/sacopy
echo "finished - see https://github.com/88lex/sasync for instructions"
exit 0