#!/bin/bash
#      1source             2dest       3trans  4check 5chnks  6SAs  7maxtran
sets=("my_movies:          bak:movies  2       20     16M     1     500"
      "my_tv:              bak:tv      2       20     16M     1     500")
numsets=$(( ${#sets[@]} ))
JSON_FOLDER=/opt/sa/
COUNT=1
MAX_JSON=20

syncsets () {
  sync=(`echo ${sets[$i]}`)
  source="${sync[0]}"
  destination="${sync[1]}"
  transfers="${sync[2]}"
  checkers="${sync[3]}"
  chunks="${sync[4]}"
  SAs="${sync[5]}"
  maxtransfers="${sync[6]}"
}

sasync () {
    if [[ "$COUNT" -gt "$MAX_JSON"  ]]; then break; fi
    echo Copying from $source to $destination using service account "$COUNT".json
#    timeout 30m\
    rclone sync $source $destination\
    --transfers $transfers --checkers $checkers\
    --max-transfer $maxtransfers\
    --drive-chunk-size $chunks\
    --fast-list -vP --stats 5s\
    --tpslimit 5 --tpslimit-burst 50 --max-backlog 1000000\
    --drive-service-account-file $JSON_FOLDER$COUNT.json
    let COUNT+=1
}

for i in $(seq 0 $(( $numsets-1 ))); do
  syncsets
  for j in $(seq 1 $SAs); do
    sasync                                                                                                                                                                    done
done
