#!/usr/bin/env bash
# Add these aliases manually to ~/.bashrc to make them permanent.
# OR run this script and these aliases will be added to ~/.bashrc for you
#
# If you don't know what this does then search for 'linux alias' on Google and read first

echo "alias sas='/opt/sasync/sasync'" >> ~/.bashrc
echo "alias csa='cd /opt/sasync'" >> ~/.bashrc
echo "alias cse='cd /opt/sasync/sets'" >> ~/.bashrc
echo "alias csl='cd /opt/sasync/logs'" >> ~/.bashrc
echo "alias csu='cd /opt/sasync/utils'" >> ~/.bashrc
echo "alias c..='cd ..'" >> ~/.bashrc
echo "alias t0='tmux a -t 0'" >> ~/.bashrc

source ~/.bashrc
