#!/usr/bin/env bash
#  #!/bin/bash
> failedmounts
readarray mounts < <( rclone listremotes | grep "$1")
for i in ${mounts[@]}; do
  echo For $i
  rclone lsd $i
  if [ $? != 0 ]
  then
    echo $i FAILED >> failedmounts
  fi
  sleep 1s
done
cat failedmounts
