#!/usr/bin/env bash
# clean_bak accepts a command line filter now.  e.g. `./clean_bak tv` will
# only delete backup folder contents in remotes that have `tv` in them
# clean_bak also passes through any rclone flags you add after the filter
# usage: ./clean_bak filter --flag1 --flag2

filter="$1"
shift
rc_flags="$@"
timeout=30m
rclone listremotes | grep "$filter"

readarray mounts < <( rclone listremotes | grep "$filter" )
for i in ${mounts[@]}; do
  echo; echo STARTING TRASH DELETE of $i; echo
  rclone cleanup $i

  echo; echo STARTING DELETE of /backup folder from $i; echo
  timeout "$timeout" rclone purge $i/backup -vP --drive-use-trash=false --fast-list \
  --tpslimit=4 --tpslimit-burst=32 --transfers=16 $rc_flags

  echo; echo FINISHED CLEAN_BAK of /backup folder from $i; echo

  # echo; echo STARTING RMDIRS of Trash folder from $i; echo
  # timeout "$timeout" rclone delete $i -v --drive-trashed-only=true --drive-use-trash=false --rmdirs --fast-list --tpslimit=4 --tpslimit-burst=16 --fast-list --transfers=16 $rc_flags
  # timeout "$timeout" rclone rmdirs $i -v --drive-trashed-only=true --drive-use-trash=false --tpslimit=4 --tpslimit-burst=32 --transfers=16 $rc_flags

done
