#!/usr/bin/env bash
# dedupe-remotes accepts a command line filter now.  e.g. `./dedupe-remotes tv` will
# only dedupe remotes that have `tv` in them

filter="$1"
shift
rc_flags="$@"
#rclone listremotes | gawk "$filter"
rclone listremotes | grep "$filter"

readarray mounts < <( rclone listremotes | grep "$filter" )
for i in ${mounts[@]}; do
  echo; echo STARTING DEDUPE of identical files from $i; echo
  rclone dedupe skip $i -v --drive-use-trash=false --no-traverse --transfers=50 $rc_flags
  rclone cleanup $i -v $rc_flags
done
