#!/bin/bash
# This script is intended to be used for initial install or a major/clean upgrade
# Installs sasync and applies ownership
# Modify below USER, GROUP and INSTALL_PATH values for your own setup
# https://github.com/88lex/sasync
# Created by Max and a925. Thank you! With a few edits from 88

# Have the script install a few apps for you. You will need git
#curl https://rclone.org/install.sh | sudo bash -s beta
sudo apt-get install zip
sudo apt-get install tmux
sudo apt-get install util-linux
sudo apt-get install git


#USER=seed
#GROUP=seed
INSTALL_PATH=/opt/sasync
# Change FALSE to TRUE if you want develop branch
DEVELOP_BRANCH=FALSE

# Make Directories
echo "Making Directories"
sudo mkdir -p $INSTALL_PATH
sudo chown -R $USER:$GROUP $INSTALL_PATH
echo "Downloading sasync"
git clone https://github.com/88lex/sasync.git $INSTALL_PATH
cd $INSTALL_PATH
if [ "$DEVELOP_BRANCH" = TRUE ] ; then
git checkout develop ; fi
cp $INSTALL_PATH/sasync.conf $INSTALL_PATH/sasync.conf.orig
cp $INSTALL_PATH/sasync.conf.default $INSTALL_PATH/sasync.conf
sudo chmod +x $INSTALL_PATH/sasync
echo "Finished - See https://github.com/88lex/sasync for instructions"
echo "Don't forget to set paths in the config"
echo "Check global defaults in the config file"
exit 0
