#!/usr/bin/env bash
# run `rc_add_remotes remote.list` where remote.list is a text/csv file with two columns
# that include `remote_name` and`teamdriveID`.
# remote_name is what you want to call your rclone remote, without a colon ':'
# teamdriveID can be copied from your browser url when at root of your teamdrive. Typically looks like `0APabc123def49PVA`

SADIR=/opt/sa

rclone_update () {
  sed '/^\s*#.*$/d' $1|\
  while read line;do set $line
    let count+=1
    rclone config update $1 type drive scope drive team_drive $2 service_account_file $SADIR/$count.json
  done; }

rclone_update $1
