#!/usr/bin/env bash
# run `rc_add_remotes remote.list` where remote.list is a text/csv file with
# two columns that include `remote_name` and`teamdriveID`.
# OR run `rc_add_remotes remote.list existing_remote_name`
# `remote_name` is what you want to call your rclone remote, without a colon ':'
# Copy `teamdriveID` from your browser url at root of teamdrive. Typically looks like `0APabc123def49PVA`
#
# Optionally, you could include `id`, `secret` and `token` in the set file if you like

SETDIR=/opt/sasets
SADIR=/opt/sa

if [ "$2" ];then
  id="client_id "`rclone config show $2|grep client_id | awk -F' = ' '{print $2}'`
  secret="client_secret "`rclone config show $2|grep client_secret | awk -F' = ' '{print $2}'`
  token="token "`rclone config show $2|grep token | awk -F' = ' '{print $2}'`
else id="";secret="";token=""
fi

rc_update () {
  sed '/^\s*#.*$/d' $SETDIR/$1|\
  while IFS= read line;do set $line
    [ "$3" ] && id="client_id $3"
    [ "$4" ] && secret="client_secret $4"
    [ "$5" ] && token="token $5"
    let count+=1
    rclone config update "${1%:*}" type drive scope drive team_drive $2 service_account_file $SADIR/$count.json $id $secret $token
  done
}

rc_update $1
