#!/usr/bin/env bash
# Written by visorask and 88lex :-)  Input from randyjc ;-)
# Usage: ./sarotate2 set.remotes  <= set.remotes is a text file with remote names, no ':'

REMOTES=`cat $1`    # REMOTES taken from the set.remotes file.
#REMOTES="$@"       # OR Use "$@" below if you prefer to specify remotes in the command line
MINJS=1             # First json file number in your JSON directory.
MAXJS=1200            # Max json file number you wish to use in your JSON directory.
JSONDIR=/opt/sa     # Location of DIR with SA .json files.
SLEEPTIME=10s        # Sleep time before switching SA .json files.
COUNT=$MINJS        # COUNT needs to be initialized.

set -x
while :
do
  echo SA Rotate is running.
  for remote in "$REMOTES";do
    rclone config update "$remote" service_account_file "$JSONDIR"/"$COUNT".json
    #systemctl restart teamdrive@"$remote".service
    COUNT=$(( $COUNT>=$MAXJS?MINJS:$COUNT+1 ))
  done
  # If you want to use the same SA for all remotes unhash the line below, hash the line above 'done'
  #COUNT=$(( $COUNT>=$MAXJS?MINJS:$COUNT+1 ))
  echo SA rotate is now going to sleep for $SLEEPTIME
  sleep $SLEEPTIME
done
